sonata_admin:
    title_logo: /bundles/sonataadmin/espunda_logo_cropped_vtiger.png
#    title: 'Espunda'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            # Customize this part to add new block configuration
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
